function modalHTML(){const s=state.draft;if(!state.modal)return'';if(state.modal==='text')return `<div class="modal-wrap" data-act="close-modal"><div class="modal" onclick="event.stopPropagation()"><h2>Chart as text</h2><p>Copyable, portable representation of the current lead sheet.</p><textarea style="height:50vh;font-family:var(--mono);font-size:12px">${esc(chartText(s))}</textarea><div class="modal-actions"><button class="btn primary" data-act="copy-chart">Copy</button><button class="btn" data-act="close-modal">Close</button></div></div></div>`;if(state.modal==='meta')return `<div class="modal-wrap" data-act="close-modal"><div class="modal" onclick="event.stopPropagation()"><h2>Sheet information</h2><p>Title and artist appear in the library, print view, and copied chart.</p><div class="modal-grid"><div class="full"><label>Title</label><input id="metaTitle" value="${esc(s.title||'')}"></div><div class="full"><label>Artist</label><input id="metaArtist" value="${esc(s.artist||'')}"></div></div><div class="modal-actions"><button class="btn primary" data-act="save-meta">Save</button><button class="btn" data-act="close-modal">Cancel</button></div></div></div>`;return `<div class="modal-wrap" data-act="close-modal"><div class="modal" onclick="event.stopPropagation()"><h2>Key, meter & feel</h2><p>Chords stay stored as scale degrees, so transposing changes labels without rewriting your progression.</p><div class="modal-grid"><div class="full"><label>Key</label><div class="subrow">${Array.from({length:12},(_,pc)=>`<button class="btn small ${s.keyPc===pc?'accent':''}" data-key="${pc}:${[1,3,6,8,10].includes(pc)?1:0}">${keyName(pc,[1,3,6,8,10].includes(pc))}</button>`).join('')}</div></div><div><label>Tonality</label><select id="mode"><option value="major" ${s.mode==='major'?'selected':''}>Major</option><option value="minor" ${s.mode==='minor'?'selected':''}>Minor</option></select></div><div><label>Time signature</label><select id="meter">${[[4,4],[3,4],[2,4],[5,4],[6,8],[7,8],[12,8]].map(([b,u])=>`<option value="${b}/${u}" ${s.bpb===b&&s.unit===u?'selected':''}>${b}/${u}</option>`).join('')}</select></div><div><label>Feel</label><input id="feel" value="${esc(s.feel||'')}" placeholder="straight, bossa, shuffle…"></div><div><label>Tempo</label><input id="modalTempo" type="number" min="30" max="280" value="${s.tempo||90}"></div><div class="full"><label>Transpose</label><div class="subrow"><button class="btn" data-act="transpose-down">− semitone</button><button class="btn" data-act="transpose-up">+ semitone</button></div></div></div><div class="modal-actions"><button class="btn primary" data-act="apply-settings">Done</button><button class="btn" data-act="close-modal">Close</button></div></div></div>`}

function wireSheetCards(root){
  root.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',()=>openSheet(el.dataset.open)));
  root.querySelectorAll('[data-dup]').forEach(el=>el.addEventListener('click',()=>duplicateSheet(el.dataset.dup)));
  root.querySelectorAll('[data-del]').forEach(el=>el.addEventListener('click',()=>{if(confirm('Delete this sheet?'))deleteSheet(el.dataset.del)}));
}
function wire(){
  document.querySelectorAll('[data-act]').forEach(el=>el.addEventListener('click',e=>act(el.dataset.act,e)));
  wireSheetCards(document);
  document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('click',()=>{state.filter=el.dataset.filter;render()}));
  $('#search')?.addEventListener('input',e=>{state.query=e.target.value;const box=$('#sheetResults');if(!box)return;box.innerHTML=libraryResultsHTML();wireSheetCards(box)});
  $('#sort')?.addEventListener('change',e=>{state.sort=e.target.value;render()});
  $('#cmajorForm')?.addEventListener('submit',e=>{e.preventDefault();addCMajor($('#cmTitle').value,$('#cmArtist').value)});
  $('#cmTitle')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#cmArtist').focus()}});
  $('#cmPick')?.addEventListener('change',e=>{state.cMajorShown=e.target.value});
  $('#cmDel')?.addEventListener('click',()=>removeCMajor($('#cmPick').value));
  if(typeof wireChordCells==='function')wireChordCells();
  else document.querySelectorAll('[data-chord]').forEach(el=>el.addEventListener('click',()=>{const [b,c]=el.dataset.chord.split(':').map(Number);selectChord(b,c)}));
  document.querySelectorAll('[data-degree]').forEach(el=>el.addEventListener('click',()=>addChord(Number(el.dataset.degree))));
  document.querySelectorAll('[data-bass]').forEach(el=>el.addEventListener('click',()=>patchActive({bass:el.dataset.bass==='none'?null:{degree:Number(el.dataset.bass),acc:''}})));
  document.querySelectorAll('[data-len]').forEach(el=>el.addEventListener('click',()=>{const c=selectedChord();if(c)patchSelected({ticks:Math.max(TPB/2,c.ticks+Number(el.dataset.len))})}));
  document.querySelectorAll('[data-piano]').forEach(el=>el.addEventListener('pointerdown',e=>{e.preventDefault();pianoPress(el.dataset.piano)}));
  document.querySelectorAll('[data-detect]').forEach(el=>el.addEventListener('click',()=>stageDetected(Number(el.dataset.detect))));
  document.querySelectorAll('[data-name]').forEach(el=>el.addEventListener('change',()=>renameBlock(Number(el.dataset.name),el.value)));
  document.querySelectorAll('[data-repeat]').forEach(el=>el.addEventListener('change',()=>setBlockRepeats(Number(el.dataset.repeat),el.value)));
  document.querySelectorAll('[data-note]').forEach(el=>el.addEventListener('change',()=>setBlockNote(Number(el.dataset.note),el.value)));
  document.querySelectorAll('[data-dup-block]').forEach(el=>el.addEventListener('click',()=>duplicateBlock(Number(el.dataset.dupBlock))));
  document.querySelectorAll('[data-del-block]').forEach(el=>el.addEventListener('click',()=>deleteBlock(Number(el.dataset.delBlock))));
  document.querySelectorAll('[data-move-block]').forEach(el=>el.addEventListener('click',()=>{const [b,d]=el.dataset.moveBlock.split(':').map(Number);moveBlock(b,d)}));
  document.querySelectorAll('[data-tempo]').forEach(el=>el.addEventListener('click',()=>updateDraft(d=>d.tempo=clamp((d.tempo||90)+Number(el.dataset.tempo),30,280),false)));
  $('#tempoInput')?.addEventListener('change',e=>updateDraft(d=>d.tempo=clamp(parseInt(e.target.value)||90,30,280),false));
  $('#volume')?.addEventListener('input',e=>{state.volume=Number(e.target.value)/100;savePrefs();e.target.nextElementSibling.textContent=Math.round(state.volume*100)+'%'});
  document.querySelectorAll('[data-key]').forEach(el=>el.addEventListener('click',()=>{const [pc,f]=el.dataset.key.split(':').map(Number);setKey(pc,!!f)}));
}
function act(a,e){switch(a){case'new-song':newSheet('transcription');break;case'new-idea':newSheet('original');break;case'back':backLibrary();break;case'export':exportAll();break;case'import':$('#importFile').click();break;case'undo':undo();break;case'redo':redo();break;case'settings':showSettings();break;case'edit-meta':state.modal='meta';render();break;case'add-block':addBlock();break;case'play':play();break;case'stop':stopPlayback();break;case'play-selected':playFromSelected();break;case'metro':state.metronome=!state.metronome;render();break;case'tap':tapTempo();break;case'toggle-labels':state.asLetters=!state.asLetters;savePrefs();render();break;case'rest':addRest();break;case'delete-chord':deleteSelected();break;case'deselect':state.selected=null;state.staged=null;render();break;case'add-staged':commitStaged();break;case'cancel-staged':cancelStaged();break;case'piano-latch':state.pianoLatch=!state.pianoLatch;render();break;case'piano-clear':clearPiano();break;case'oct-down':Object.keys(audio.live).forEach(liveOff);state.pianoHeld=[];state.pianoOctave=Math.max(-2,state.pianoOctave-1);render();break;case'oct-up':Object.keys(audio.live).forEach(liveOff);state.pianoHeld=[];state.pianoOctave=Math.min(2,state.pianoOctave+1);render();break;case'copy-chart':copyChart();break;case'print':window.print();break;case'close-modal':state.modal=null;render();break;case'save-meta':saveMetaFromModal();break;case'transpose-down':transpose(-1);break;case'transpose-up':transpose(1);break;case'apply-settings':{const [b,u]=$('#meter').value.split('/').map(Number),mode=$('#mode').value,feel=$('#feel').value,tempo=clamp(parseInt($('#modalTempo').value)||90,30,280);updateDraft(d=>{d.bpb=b;d.unit=u;d.mode=mode;d.feel=feel.slice(0,40);d.tempo=tempo},false);state.modal=null;render();break}}}
$('#importFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importJson(f);e.target.value=''})
window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if(state.view!=='editor')return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.code==='Space'){e.preventDefault();state.playing?stopPlayback():play();return}if(e.key==='Enter'){if(state.staged){e.preventDefault();commitStaged();return}const info=pianoInfo();if(info.matches.length){e.preventDefault();stageDetected(0);commitStaged();return}}const pk=PIANO_KEYS.indexOf(e.key.toLowerCase());if(pk>=0){e.preventDefault();pianoPress(pk);return}if(/^[1-7]$/.test(e.key)){e.preventDefault();addChord(Number(e.key))}if(e.key==='Escape'){if(state.staged){cancelStaged()}else if(state.selected){state.selected=null;render()}}if((e.key==='Backspace'||e.key==='Delete')&&state.selected){e.preventDefault();deleteSelected()}});
window.addEventListener('beforeunload',()=>{if(state.draft)try{localStorage.setItem(DRAFT_KEY,JSON.stringify(state.draft))}catch(e){}});
load();
