function addChord(degree){const d=state.draft;if(!d)return; if(state.selected){updateDraft(x=>{const c=x.blocks[state.selected.b].chords[state.selected.c],ticks=c.ticks;x.blocks[state.selected.b].chords[state.selected.c]={degree,acc:'',quality:null,bass:null,ticks}});previewChord(selectedChord());return}updateDraft(x=>{const b=x.blocks[x.blocks.length-1],bt=x.bpb*TPB,used=b.chords.reduce((a,c)=>a+c.ticks,0),room=bt-(used%bt||0);b.chords.push({degree,acc:'',quality:null,bass:null,ticks:room||bt});state.selected={b:x.blocks.length-1,c:b.chords.length-1}});previewChord(selectedChord())}
function addRest(){if(state.selected){patchSelected({rest:true,degree:undefined,acc:undefined,quality:undefined,bass:undefined});return}updateDraft(x=>{const b=x.blocks[x.blocks.length-1],bt=x.bpb*TPB,used=b.chords.reduce((a,c)=>a+c.ticks,0),room=bt-(used%bt||0);b.chords.push({rest:true,ticks:room||bt});state.selected={b:x.blocks.length-1,c:b.chords.length-1}})}
function deleteSelected(){if(!state.selected)return;const {b,c}=state.selected;updateDraft(d=>d.blocks[b].chords.splice(c,1));state.selected=null;render()}
function addBlock(){updateDraft(d=>d.blocks.push(blankBlock()));setTimeout(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}),0)}
function duplicateBlock(bi){updateDraft(d=>{const b=clone(d.blocks[bi]);b.id=uid('b');d.blocks.splice(bi+1,0,b)});}
function moveBlock(bi,dir){const j=bi+dir;if(j<0||j>=state.draft.blocks.length)return;updateDraft(d=>[d.blocks[bi],d.blocks[j]]=[d.blocks[j],d.blocks[bi]]);if(state.selected?.b===bi)state.selected.b=j;else if(state.selected?.b===j)state.selected.b=bi}
function deleteBlock(bi){if(state.draft.blocks.length===1)return;if(!confirm('Delete this section?'))return;updateDraft(d=>d.blocks.splice(bi,1));state.selected=null;render()}
function renameBlock(bi,val){updateDraft(d=>d.blocks[bi].name=val,false)}
function setBlockRepeats(bi,v){updateDraft(d=>d.blocks[bi].repeats=clamp(parseInt(v)||1,1,32),false)}
function setBlockNote(bi,v){updateDraft(d=>d.blocks[bi].note=v.slice(0,100),false)}

function ensureAudio(){if(!audio.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audio.ctx=new C();const comp=audio.ctx.createDynamicsCompressor();comp.threshold.value=-16;comp.knee.value=24;comp.ratio.value=7;comp.attack.value=.003;comp.release.value=.16;comp.connect(audio.ctx.destination);audio.bus=comp}if(audio.ctx.state==='suspended')audio.ctx.resume();return audio.ctx}
function stopNodes(){audio.nodes.forEach(n=>{try{n.stop()}catch(e){}});audio.nodes=[]}
function midiFreq(m){return 440*Math.pow(2,(m-69)/12)}
function tone(midi,at,dur,level=.1,type='triangle'){const ctx=ensureAudio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=midiFreq(midi);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(level*state.volume,at+.012);g.gain.setValueAtTime(level*state.volume,Math.max(at+.015,at+dur-.12));g.gain.exponentialRampToValueAtTime(.0001,at+dur);o.connect(g).connect(audio.bus);o.start(at);o.stop(at+dur+.03);audio.nodes.push(o)}
function liveOn(id,midi){const ctx=ensureAudio();if(!ctx||audio.live[id])return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.value=midiFreq(midi);g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.13*state.volume,ctx.currentTime+.015);o.connect(g).connect(audio.bus);o.start();audio.live[id]={o,g}}
function liveOff(id){const v=audio.live[id];if(!v||!audio.ctx)return;delete audio.live[id];try{const t=audio.ctx.currentTime;v.g.gain.cancelScheduledValues(t);v.g.gain.setValueAtTime(Math.max(.0001,v.g.gain.value),t);v.g.gain.exponentialRampToValueAtTime(.0001,t+.12);v.o.stop(t+.14)}catch(e){}}
function clearPiano(){Object.keys(audio.live).forEach(liveOff);state.pianoHeld=[];render()}
function pianoPress(semi){semi=Number(semi);const on=state.pianoHeld.includes(semi);if(state.pianoLatch&&on){state.pianoHeld=state.pianoHeld.filter(x=>x!==semi);liveOff('p'+semi)}else{if(!on)state.pianoHeld=[...state.pianoHeld,semi].sort((a,b)=>a-b);liveOn('p'+semi,pianoBase()+semi)}render()}
function commitDetected(i=0){const info=pianoInfo(),m=info.matches[i];if(!m)return;const chord=detectedToChord(m,info.bass,state.draft);if(state.selected){const ticks=selectedChord().ticks;updateDraft(d=>{d.blocks[state.selected.b].chords[state.selected.c]={...chord,ticks}})}else{updateDraft(d=>{const b=d.blocks[d.blocks.length-1],bt=d.bpb*TPB,used=b.chords.reduce((a,c)=>a+c.ticks,0),room=bt-(used%bt||0);b.chords.push({...chord,ticks:room||bt});state.selected={b:d.blocks.length-1,c:b.chords.length-1}})}clearPiano();previewChord(selectedChord())}

function voiceChord(c,s){if(c.rest)return[];const root=(s.keyPc+degreePc(c.degree,c.acc,s.mode))%12;const q=actualQuality(c,s.mode);const ivs=QUALITY_IVS[q]||[0,4,7];let base=48+root;while(base<48)base+=12;while(base>59)base-=12;return ivs.map((iv,i)=>base+12+iv).concat(c.bass?[36+((s.keyPc+degreePc(c.bass.degree,c.bass.acc,s.mode))%12)]:[base])}
function previewChord(c){if(!c||c.rest)return;const ctx=ensureAudio();if(!ctx)return;stopNodes();voiceChord(c,state.draft).forEach((m,i)=>tone(m,ctx.currentTime+.015,.55,i===0?.09:.06))}
function playbackItems(s){const items=[];let tick=0;s.blocks.forEach((b,bi)=>{for(let r=0;r<Math.max(1,b.repeats||1);r++){b.chords.forEach((c,ci)=>{items.push({chord:c,start:tick,ticks:c.ticks,bi,ci});tick+=c.ticks})}});return {items,total:tick}}
function stopPlayback(){state.playing=false;state.playPos=-1;stopNodes();if(audio.raf)cancelAnimationFrame(audio.raf);audio.raf=null;render()}
function play(){const s=state.draft;if(!s)return;const ctx=ensureAudio();if(!ctx)return;stopPlayback();const plan=playbackItems(s);if(!plan.items.length)return;const spt=60/(s.tempo||90)/TPB,startAt=ctx.currentTime+.12;plan.items.forEach(it=>{if(it.chord.rest)return;voiceChord(it.chord,s).forEach((m,i)=>tone(m,startAt+it.start*spt,Math.max(.08,it.ticks*spt-.02),i===0?.075:.045))});if(state.metronome){const bt=s.bpb*TPB;for(let t=0;t<plan.total;t+=TPB){const accent=t%bt===0;tone(accent?84:79,startAt+t*spt,.045,accent?.055:.035,'square')}}state.playing=true;state.playPlan={...plan,startAt,spt};const step=()=>{if(!state.playing)return;const pos=(ctx.currentTime-startAt)/spt;state.playPos=pos;if(pos>=plan.total){state.playing=false;state.playPos=-1;render();return}renderPlaying();audio.raf=requestAnimationFrame(step)};audio.raf=requestAnimationFrame(step);render()}
function renderPlaying(){document.querySelectorAll('.chord-cell.playing').forEach(x=>x.classList.remove('playing'));document.querySelectorAll('.section.playing').forEach(x=>x.classList.remove('playing'));const p=state.playPlan;if(!p||state.playPos<0)return;const it=p.items.find(x=>state.playPos>=x.start&&state.playPos<x.start+x.ticks);if(!it)return;const cell=document.querySelector(`[data-chord="${it.bi}:${it.ci}"]`);if(cell){cell.classList.add('playing');cell.closest('.section')?.classList.add('playing')}}
function playFromSelected(){if(!state.selected){play();return}const plan=playbackItems(state.draft);let offset=0;for(const it of plan.items){if(it.bi===state.selected.b&&it.ci===state.selected.c){offset=it.start;break}}const ctx=ensureAudio();if(!ctx)return;stopPlayback();const s=state.draft,spt=60/(s.tempo||90)/TPB,startAt=ctx.currentTime+.12;plan.items.filter(it=>it.start+it.ticks>offset).forEach(it=>{if(it.chord.rest)return;voiceChord(it.chord,s).forEach((m,i)=>tone(m,startAt+Math.max(0,it.start-offset)*spt,Math.max(.08,(it.start+it.ticks-Math.max(it.start,offset))*spt-.02),i===0?.075:.045))});state.playing=true;state.playPlan={...plan,startAt,spt,offset};const step=()=>{if(!state.playing)return;const pos=offset+(ctx.currentTime-startAt)/spt;state.playPos=pos;if(pos>=plan.total){state.playing=false;state.playPos=-1;render();return}renderPlaying();audio.raf=requestAnimationFrame(step)};audio.raf=requestAnimationFrame(step);render()}
let taps=[];function tapTempo(){const now=performance.now();taps=taps.filter(x=>now-x<2500);taps.push(now);if(taps.length>1){const gaps=taps.slice(1).map((x,i)=>x-taps[i]);const avg=gaps.reduce((a,b)=>a+b)/gaps.length;updateDraft(d=>d.tempo=clamp(Math.round(60000/avg),30,280),false)}else toast('Tap a few times')}

function render(){app.innerHTML=state.view==='library'?libraryHTML():editorHTML();wire();renderToast();if(state.playing)renderPlaying()}
function renderTopOnly(){const x=$('#saveIndicator');if(x)x.textContent=state.saveState==='saving'?'saving…':state.saveState==='saved'?'saved':'local';}
function topbarHTML(editor=false){return `<header class="topbar"><div class="topbar-inner"><div class="brand" ${!editor?'style="cursor:default"':''}><img src="apple-touch-icon.png" alt=""><div class="brand-copy"><div class="brand-title">Lead Sheets</div><div class="brand-sub">listen · capture · formulate</div></div></div><div class="top-actions">${editor?`<span id="saveIndicator" class="save-indicator">${state.saveState==='saving'?'saving…':state.saveState==='saved'?'saved':'local'}</span><button class="btn ghost-dark small" data-act="undo" ${state.undo.length?'':'disabled'}>↶ <span class="long">Undo</span></button><button class="btn ghost-dark small" data-act="redo" ${state.redo.length?'':'disabled'}>↷ <span class="long">Redo</span></button><button class="btn ghost-dark small" data-act="settings">Key / Meter</button>`:''}</div></div></header>`}
function libraryHTML(){let shown=state.sheets.filter(s=>(state.filter==='all'||(s.kind||'transcription')===state.filter)&&(`${s.title||''} ${s.artist||''} ${s.keyName||''}`).toLowerCase().includes(state.query.toLowerCase()));const sorters={recent:(a,b)=>(b.savedAt||0)-(a.savedAt||0),title:(a,b)=>(a.title||'').localeCompare(b.title||''),artist:(a,b)=>(a.artist||'').localeCompare(b.artist||''),key:(a,b)=>(a.keyName||'').localeCompare(b.keyName||'')};shown.sort(sorters[state.sort]);const ideas=state.sheets.filter(s=>s.kind==='original').length,bars=state.sheets.reduce((n,s)=>n+barsCount(s),0);return `${topbarHTML()}<main class="shell"><section class="hero"><h1>Turn listening into a chart.</h1><p>Capture harmony quickly, keep the form readable, and transpose without rewriting a single chord.</p><div class="hero-actions"><button class="btn primary" data-act="new-song">＋ Transcribe a song</button><button class="btn accent" data-act="new-idea">✦ Start an idea</button></div></section>${state.sheets.length?`<div class="stats"><div class="stat"><b>${state.sheets.length}</b><span>Sheets</span></div><div class="stat"><b>${bars}</b><span>Charted bars</span></div><div class="stat"><b>${ideas}</b><span>Original ideas</span></div></div>`:''}<div class="toolbar"><div class="search"><input id="search" value="${esc(state.query)}" placeholder="Search title, artist, key…"></div><div class="segment">${[['all','All'],['transcription','Songs'],['original','Ideas']].map(([k,l])=>`<button data-filter="${k}" class="${state.filter===k?'active':''}">${l}</button>`).join('')}</div><select id="sort"><option value="recent" ${state.sort==='recent'?'selected':''}>Recent</option><option value="title" ${state.sort==='title'?'selected':''}>Title</option><option value="artist" ${state.sort==='artist'?'selected':''}>Artist</option><option value="key" ${state.sort==='key'?'selected':''}>Key</option></select></div>${shown.length?`<div class="sheet-grid">${shown.map(sheetCardHTML).join('')}</div>`:`<div class="empty"><b>${state.sheets.length?'No matching sheets.':'Your collection is empty.'}</b>${state.sheets.length?'Try a different search or filter.':'Put on a song, identify the harmony, and drop each chord into place.'}</div>`}<div class="backup"><div class="backup-copy"><b>Backup & transfer</b><span>Your library stays in this browser unless you export it.</span></div><div class="card-actions"><button class="btn" data-act="export">Download JSON</button><button class="btn" data-act="import">Import JSON</button></div></div></main>`}
